# Generated by Django 5.2.3 on 2025-08-26 18:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название устройства', max_length=100, verbose_name='Device Name')),
                ('model', models.CharField(help_text='Модель устройства', max_length=100, verbose_name='Device Model')),
                ('serial_number', models.CharField(db_index=True, help_text='Серийный номер устройства', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Serial Number')),
                ('device_type', models.CharField(choices=[('lamp', 'Lamp'), ('sensor', 'Sensor'), ('switch', 'Switch'), ('controller', 'Controller'), ('other', 'Other')], default='other', help_text='Тип устройства', max_length=20, verbose_name='Device Type')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='offline', help_text='Текущий статус устройства', max_length=20, verbose_name='Status')),
                ('firmware_version', models.CharField(blank=True, help_text='Версия прошивки', max_length=50, null=True, verbose_name='Firmware Version')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес устройства', null=True, verbose_name='IP Address')),
                ('mqtt_topic', models.CharField(help_text='Топик MQTT для устройства', max_length=200, verbose_name='MQTT Topic')),
                ('last_message_received', models.DateTimeField(blank=True, help_text='Время получения последнего сообщения', null=True, verbose_name='Last Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время последнего обновления', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли устройство', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_number'], name='lamp_device_serial__152f5e_idx'), models.Index(fields=['status'], name='lamp_device_status_793046_idx'), models.Index(fields=['device_type'], name='lamp_device_device__cdb12b_idx')],
            },
        ),
    ]
